#!/usr/bin/env python3
"""
embed_assets.py — Convert ui/dist/ into src/webui/assets.h

Usage:
  python3 src/webui/embed_assets.py                  # ui/dist → src/webui/assets.h
  python3 src/webui/embed_assets.py <dist> <output>  # custom paths

Run after:
  cd src/webui/ui && npm run build
"""

import os
import sys

MIME_TYPES = {
    '.html': 'text/html; charset=UTF-8',
    '.css':  'text/css',
    '.js':   'application/javascript',
    '.mjs':  'application/javascript',
    '.json': 'application/json',
    '.svg':  'image/svg+xml',
    '.png':  'image/png',
    '.ico':  'image/x-icon',
    '.woff': 'font/woff',
    '.woff2':'font/woff2',
    '.ttf':  'font/ttf',
}

def escape_bytes(data: bytes) -> str:
    """Escape binary data for a C string literal."""
    parts = []
    prev_was_question = False
    for b in data:
        if b == ord('\\'):
            parts.append('\\\\')
            prev_was_question = False
        elif b == ord('"'):
            parts.append('\\"')
            prev_was_question = False
        elif b == ord('\n'):
            parts.append('\\n')
            prev_was_question = False
        elif b == ord('\r'):
            parts.append('\\r')
            prev_was_question = False
        elif b == ord('\t'):
            parts.append('\\t')
            prev_was_question = False
        elif b == ord('?'):
            # Escape the second '?' in a '??' pair to prevent trigraph sequences.
            if prev_was_question:
                parts.append('\\?')
            else:
                parts.append('?')
            prev_was_question = True
        elif 32 <= b < 127:
            parts.append(chr(b))
            prev_was_question = False
        else:
            # Use octal escapes (\NNN) — always exactly 3 digits, no greedy-parsing
            # ambiguity unlike \xNN which merges with adjacent hex digits.
            parts.append(f'\\{b:03o}')
            prev_was_question = False
    return '"' + ''.join(parts) + '"'

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    dist_dir   = sys.argv[1] if len(sys.argv) > 1 else os.path.join(script_dir, 'ui', 'dist')
    out_file   = sys.argv[2] if len(sys.argv) > 2 else os.path.join(script_dir, 'assets.h')

    if not os.path.isdir(dist_dir):
        print(f'Error: dist directory not found: {dist_dir}', file=sys.stderr)
        print('Run: cd src/webui/ui && npm run build', file=sys.stderr)
        sys.exit(1)

    assets = []
    for root, _dirs, files in os.walk(dist_dir):
        for filename in sorted(files):
            filepath = os.path.join(root, filename)
            rel_path = os.path.relpath(filepath, dist_dir).replace(os.sep, '/')
            ext  = os.path.splitext(filename)[1].lower()
            mime = MIME_TYPES.get(ext, 'application/octet-stream')
            with open(filepath, 'rb') as f:
                data = f.read()
            assets.append((rel_path, data, mime))

    lines = [
        '// Copyright (c) 2025-present The Avian Core developers',
        '// Distributed under the MIT software license, see the accompanying',
        '// file COPYING or https://opensource.org/license/mit/.',
        '//',
        '// Generated by embed_assets.py — DO NOT EDIT',
        '// Rebuild with: python3 src/webui/embed_assets.py ui/dist src/webui/assets.h',
        '',
        '#pragma once',
        '#include <string_view>',
        '#include <unordered_map>',
        '',
        'struct WebUIAsset {',
        '    std::string_view content;',
        '    std::string_view content_type;',
        '};',
        '',
        '// clang-format off',
        'inline const std::unordered_map<std::string_view, WebUIAsset>& GetEmbeddedAssets()',
        '{',
    ]

    var_names = []
    for rel_path, data, mime in assets:
        var = 'ASSET_' + rel_path.upper().replace('/', '_').replace('.', '_').replace('-', '_')
        var_names.append((rel_path, var, mime))
        content_str = escape_bytes(data)
        lines.append(f'    static const char {var}[] = {content_str};')

    lines += [
        '',
        '    static const std::unordered_map<std::string_view, WebUIAsset> s_assets{',
    ]
    for rel_path, var, mime in var_names:
        lines.append(f'        {{"{rel_path}", {{std::string_view{{{var}, sizeof({var})-1}}, "{mime}"}}}},')
    lines += [
        '    };',
        '    return s_assets;',
        '}',
        '// clang-format on',
        '',
    ]

    with open(out_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    total = sum(len(d) for _, d, _ in assets)
    print(f'Embedded {len(assets)} files ({total:,} bytes) -> {out_file}')

if __name__ == '__main__':
    main()
