#ifndef AVIAN_CHAINPARAMSSEEDS_H
#define AVIAN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the avian network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
};

static const uint8_t chainparams_seed_signet[] = {
};

static const uint8_t chainparams_seed_test[] = {
};

static const uint8_t chainparams_seed_testnet4[] = {
};
#endif // AVIAN_CHAINPARAMSSEEDS_H
