name: 'Build & Check: macOS Full QT'

on: [push]

jobs:
  build:
    runs-on: macos-10.15
    strategy:
        matrix:
          os: [x86_64-mac]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Brew Install Dependencies
        run: brew install automake pandoc

      - name: Dependencies
        run: |
          cd depends
          make -j3
          cd ..

      - name: Install pypandoc
        run: pip3 install pypandoc

      - name: Auto Generate
        run: ./autogen.sh

      - name: Configure
        run: CONFIG_SITE=$PWD/depends/x86_64-apple-darwin19.6.0/share/config.site ./configure

      - name: Make
        run: make -j3

      - name: Make Check
        run: make check

      - name: Upload Test Suite Log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-suite-log
          path: /src/test-suite.log