name: Dependencies - Arm32v7

on:
  pull_request:
    branches:
      - depends
    paths:
      - 'depends/**'
  push:
    branches:
      - depends
    paths:
      - 'depends/**'

env:
  OS: arm32v7
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${OS}

    - name: Build the Dependencies
      run: cd depends && make HOST=arm-linux-gnueabihf -j2

    - name: Tar Up the Dependencies
      run: |
          if [[ ! -e ${{ GITHUB.WORKSPACE }}/depends_temp ]]; then mkdir -p ${{ GITHUB.WORKSPACE }}/depends_temp; fi
          cd ${{ GITHUB.WORKSPACE }}/depends && tar zcf ${{ GITHUB.WORKSPACE }}/depends_temp/avian-arm32v7-dependencies.tar.gz .
          cd ${{ GITHUB.WORKSPACE }}/depends_temp
          if [[ -e avian-arm32v7-dependencies.tar.gz ]]; then sha256sum avian-arm32v7-dependencies.tar.gz > SHASUM; else echo "no dependency tar file found"; fi

    - name: Sync the Dependencies to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: "${{ GITHUB.WORKSPACE }}/depends_temp/"
        DEST_DIR: 'arm'
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

