name: Dependencies - Mac OS X

on:
  pull_request:
    branches:
      - depends
    paths:
      - 'depends/**'
  push:
    branches:
      - depends
    paths:
      - 'depends/**'

env:
  OS: osx
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${OS}

    - name: Copy the Xcode Dependency Files
      run: |
          cd ${{ GITHUB.WORKSPACE }}
          curl -O https://avian-build-resources.avian.network/osx/MacOSX10.11.sdk.tar.gz

    - name: Extract Xcode Resources
      run: |
          mkdir -p ${{ GITHUB.WORKSPACE }}/depends/SDKs
          cd ${{ GITHUB.WORKSPACE }}/depends/SDKs && tar -zxf ${{ GITHUB.WORKSPACE }}/MacOSX10.11.sdk.tar.gz

    - name: Build the Dependencies
      run: cd ${{ GITHUB.WORKSPACE }}/depends && make HOST=x86_64-apple-darwin14 -j2

    - name: Tar Up the Dependencies
      run: |
          if [[ ! -e ${{ GITHUB.WORKSPACE }}/depends_temp ]]; then mkdir -p ${{ GITHUB.WORKSPACE }}/depends_temp; fi
          cd ${{ GITHUB.WORKSPACE }}/depends && tar zcf ${{ GITHUB.WORKSPACE }}/depends_temp/avian-osx-dependencies.tar.gz .
          cd ${{ GITHUB.WORKSPACE }}/depends_temp
          if [[ -e avian-osx-dependencies.tar.gz ]]; then sha256sum avian-osx-dependencies.tar.gz > SHASUM; else echo "no dependency tar file found"; fi

    - name: Sync the Dependencies to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: "${{ GITHUB.WORKSPACE }}/depends_temp/"
        DEST_DIR: 'osx'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: "avian-build-resources"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
