name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: >
       sudo apt-get install build-essential libboost-dev libboost-all-dev libssl-dev
       libdb++-dev libminiupnpc-dev libleveldb-dev -y protobuf-compiler
    - name: autogen
    - run : ./autogen.sh
    - name: configure
      run: ./configure --with-incompatible-bdb
    - name: make
      run: make
